### ISSUE TITLE
MQTT Communication

### ISSUE THREAD

**Issue by tinchom** [awslabs/aws-greengrass-labs-component-for-home-assistant#17]
Hi Greg,

I have deployment up and running with more components. Now we are in the phase of communication and i have a doubt about the following step:

We can use the [MQTT Integration](https://www.home-assistant.io/integrations/mqtt/) to connect Home Assistant directly to AWS IoT Core. Firstly create a Thing representing Home Assistant, and obtain the device certificate, private key and CA certificate.

The question is: 
Do I have to create a new certificate inside the "Thing" and then download and move it to the location where the secret folder is located?

Thanks!

**Comment by gregbreen** [comment]
Hi. Have you tried to follow the instructions here?

https://github.com/awslabs/aws-greengrass-labs-component-for-home-assistant#aws-iot-core

So with that approach I am suggesting to add it to the secret.

**Comment by tinchom** [comment]
Greg,

Thats what i'm talking about... My doubt is if i have to had two Things for one Greengrass core device...

Thanks again.

**Comment by MikeDombo** [comment]
Hello @tinchom,
Yes you should have 2 different things. One for Greengrass, one for home assistant in this case.

**Comment by tinchom** [comment]
Thanks Mike.
Last question (i think):

Its possible to see the home-assistant activity in aws IoT core portal (MQTT test client)?

My hw is Raspberry Pi with Sonoff anthena Zigbee and wireless open door sensor.
We would like to know if its possible to see that activity (open/close) in the end point devices.

Thanks again!
Martin

**Comment by MikeDombo** [comment]
If the home assistant MQTT client is publishing messages to IoT Core, then you'd see those if you subscribe to the appropriate topics in the test client. I personally do not know what topics would be relevant, but I'm sure that home assistant would document those.
