### ISSUE TITLE
deploy_component_version.py overwrites existing Core Device Deployment

### ISSUE THREAD

**Issue by kenjfox** [awslabs/aws-greengrass-labs-component-for-home-assistant#4]
If you run this on a core device with an existing device-specific deployment with any other name, it will overwrite it without incorporating the components from the existing deployment.
In my example, I had a deployment named "VangoGGCore_CLI" with a single cli component.  After running this script, the name was changed to "Deployment for VangoGGCore" with only the required components for the home assistant component.
According to AWS, Core Devices are limited to a single deployment, and creating another core-device-specific deployment will automatically overwrite the existing one.  There is no warning message.  
I made some modifications to the script to simply grab the latest device-specific deployment regardless of its name, and add the Home Assistant components to it.  I'll send a PR.

**Comment by gregbreen** [comment]
Thanks @kenjfox . As fate would have it, I was working on this problem yesterday. I will publish a fix today.

**Comment by pallavi03** [comment]
Closing the issue as code is merged
